version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: swapp
      MYSQL_USER: swapp
      MYSQL_PASSWORD: swapp
      MYSQL_ROOT_PASSWORD: swapp
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: awac
      PMA_PASSWORD: awac
    ports:
      - "8080:80"  
      
  web:
    build: ./
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql